### ISSUE TITLE
Error of "Bad output excel2007 file" and the data lost in excel97

### ISSUE THREAD

**Issue by frankies** [hishidama/embulk-formatter-poi_excel#2]
## Embulk version
v0.9.23

### Data 
I use postgresql jdbc as the input.
The importing data script:

```sql
create table demo(no integer);
insert into demo(no) select * FROM generate_series(1,20000);
```
### Embulk script
- test.yml.liquid
```yaml
exec:
  max_threads: 1
  min_output_tasks: 1

in:
  type: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: test
  schema: public
  query: select no from demo order by 1

out:
  type: file
  path_prefix: out.xlsx
  file_ext: "test.xls"
  sequence_format: ""
  formatter:
    type: poi_excel
    spread_sheet_version: EXCEL2007
    sheet_name: Sheet1
```
The **spread_sheet_version** field can be "`EXCEL97`" or "`EXCEL2007`".

## Command 

```bash
embulk run test.yml.liquid
```

### BUG 

- When the `spread_sheet_version` field is `EXCEL97`
  The file can be opened, but the count of rows is wrong, it's only 1820. Actually, it must be 20000.

- When the `spread_sheet_version` field is `EXCEL2007`
The file can not be opened.  It reports the following error:

![output-2007-error-badfile](https://user-images.githubusercontent.com/2113812/94382751-7670c900-0170-11eb-9cd6-0f84e0255701.png)

The other way,  according to the POI office recommends that to use the class '`org.apache.poi.xssf.streaming.SXSSFWorkbook`' resolve the mass data, avoiding the out of memory error.

### Improvement advise
The code needs more logs

## Attachments

[output-logs-files-error.zip](https://github.com/hishidama/embulk-formatter-poi_excel/files/5289514/output-logs-files-error.zip)

That's all.
